### ISSUE TITLE
Login page

### ISSUE THREAD

**Issue by hussamEL-Hwary** [dane-hillard-photography/dhp#56]
The footer in login page isn't at the bottom of the page

**Comment by daneah** [comment]
@hussamEL-Hwary thanks for opening this issue. This is currently working as intended; the footer is not sticky on this site. I may consider creating a sticky footer at some point, but I don't have the bandwidth at the moment! I'd be happy to incorporate a pull request from you if you have time!

**Comment by daneah** [comment]
@hussamEL-Hwary thanks for opening this issue. This is currently working as intended; the footer is not sticky on this site. I may consider creating a sticky footer at some point, but I don't have the bandwidth at the moment! I'd be happy to incorporate a pull request from you if you have time!
